# Generated by Django 5.1.4 on 2024-12-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pass1_user_pass2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default='Unknown Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pass1',
            field=models.CharField(default='password1234', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='pass2',
            field=models.CharField(default='password1234', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=200, unique=True),
        ),
    ]
