# Generated by Django 5.1.4 on 2024-12-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='user',
        ),
    ]
