# Generated by Django 5.1.4 on 2024-12-28 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_missingperson_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
