# Generated by Django 5.1.4 on 2024-12-28 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_missingperson_gender_alter_missingperson_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='user',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=255),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='case_registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='case_registered_by',
            field=models.CharField(default='Admin', max_length=255),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
